# Generated by Django 5.2.10 on 2026-01-13 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('one_line_desc', models.CharField(max_length=500)),
                ('freshers_desc', models.TextField()),
                ('experienced_desc', models.TextField()),
                ('svg_d_value', models.TextField(help_text='ONLY SVG path d attribute value')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_careers', to='users.user')),
            ],
            options={
                'db_table': 'careers',
                'ordering': ['-updated_at'],
            },
        ),
    ]
